export const ADD_CONFIG_TITLE = '添加参数'
export const EDIT_CONFIG_TITLE = '修改参数'
export const ADD_DICT_TITLE = '添加字典数据'
export const EDIT_DICT_TITLE = '修改字典数据'
export const ADD_DICTTYPE_TITLE = '添加字典数据'
export const EDIT_DICTTYPE_TITLE = '修改字典数据'
export const ADD_MENU_TITLE = '添加菜单'
export const EDIT_MENU_TITLE = '修改菜单'